# Generated by Django 2.1.2 on 2019-07-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0002_auto_20190722_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
