# Generated by Django 2.1.2 on 2019-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electives', '0003_auto_20190723_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
